### PR TITLE
[ate] fixes #145 and #146

### LINKED ISSUE #145: potential overflow in function TokensCopy in file ate_dll.cc
in line 286 memcpy(resp_token.data, token.c_str(), sizeof(resp_token.data)); the size of memcpy should be resp_token.size since in line 285 we update resp_token.size to be token.size() and  sizeof(resp_token.data) can be more.
the same issue is in line 306 memcpy(seed.seed, s.c_str(), sizeof(seed.seed)); the size should be seed.size as it updates in line 305

### LINKED ISSUE #146: wrong size for sku_specific parameter in struct DeviceId in file ate_api.h
in line 78 the parameter definition of sku_specific is uint8_t sku_specific[kSkuSpecificSize];
the size of sku_specific is 128 bits while kSkuSpecificSize is defined as  kSkuSpecificSize = 128, in line 25 
it should be  kSkuSpecificSize = 16

### PR DESCRIPTION
**Pull request by timothytrippel**
This PR contains two commits that fixes #145 and fixes #146.

### CODE REVIEW

**Review by shmulik-h — APPROVED** [review]

File: src/ate/ate_dll.cc [hunk 1]
```diff
@@ -283,7 +283,7 @@ int TokensCopy(size_t count, const pa::DeriveTokensResponse &resp,
     }
 
     resp_token.size = token.size();
-    memcpy(resp_token.data, token.c_str(), sizeof(resp_token.data));
+    memcpy(resp_token.data, token.c_str(), resp_token.size);
```
Comment (cfrantz) [inline src/ate/ate_dll.cc:286]: Why `c_str()` here?  The `size` doesn't include the `nul` terminator and `c_str` provides a pointer to a buffer that will provide it.  I think `data()` is more appropriate here.

We currently have error checking to ensure that the `token.size()` is not larger than the target buffer (`resp_token.data`).  Is it possible that `token.size()` might be too shorter than `sizeof(resp_token.data)`, and if so:
- What is the appropriate data pattern for the rest of `resp_token.data`?
- Who is responsible for setting or initializing that portion of `resp_token.data`?

**Review by cfrantz — APPROVED** [review]
